miniprojecte/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings

urlpatterns =([
    url(r'^', include('testsforall.urls', namespace="testsforall")),
    ]
    + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

testsforall/urls.py
from django.conf.urls import url

from . import views
from usuarios.views import views_signin, views_signup, views_checkuser, views_checkmail, views_confirmmail
urlpatterns = [
    url(r'^solvetest', views.solveTest, name = "solveTest"),
    url(r'^getsurveystodo', views.getSurveysToDo, name = "getSurveysToDo"),
    url(r'^surveystodo$', views.surveysToDo, name = "surveysToDo"),
    url(r'^getmygroups', views.getMyGroups, name = "getMyGroups"),
    url(r'^creategroup', views.createGroup, name = "createGroup"),
    url(r'^user/(?P<idUser>[0-9]+)/', views.user, name = "user"),
    url(r'^friendrequests', views.friendRequests, name = "friendRequests"),
    url(r'^sendfriendrequest', views.sendFriendRequest, name = "sendFriendRequest"),
    url(r'^acceptfriend', views.acceptFriend, name = "acceptFriend"),
    url(r'^getusers$', views.getUsers, name = "getUsers"),
    url(r'^getfriendrequests', views.getFriendRequests, name = "getFriendRequests"),
    url(r'^getfriends$', views.getFriends, name = "getFriends"),
    url(r'^social', views.social, name = "social"),
    url(r'^confirmmail/(?P<hashlink>[a-fA-F\d]*)/(?P<userid>[0-9]+)', views_confirmmail, name="confirmmail"),
    url(r'^checkmail$', views_checkmail, name="checkmail"),
    url(r'^checkuser$', views_checkuser, name="checkuser"),
    url(r'^saveanswer$', views.save_answer, name = "save_answer"),
    url(r'^savequestion$', views.save_question, name = "save_question"),
    url(r'^editsurvey/(?P<idSurvey>[0-9]+)/', views.edit_survey, name = "edit_survey"),
    url(r'^publish/(?P<idSurvey>[0-9]+)/', views.publish_survey, name = "publish_survey"),
    url(r'^getsurveys$', views.getSurveys, name = "getSurveys"),
    url(r'^misencuestas$', views.mySurveys, name = "mySurveys"),
    url(r'^deletesurvey/(?P<idSurvey>[0-9]+)/', views.deleteSurvey, name = "deleteSurvey"),
    url(r'^survey/(?P<idSurvey>[0-9]+)/', views.survey, name = "survey"),
    url(r'^$', views.index, name="index"),
    url(r'^upload$', views.upload, name ='jfu_upload'),
    url(r'^upload/(?P<idSurvey>[0-9]+)$', views.upload, name = 'jfu_upload_edit'),
    url(r'^deleteupload/(?P<pk>\d+)$', views.upload_delete, name ='jfu_delete'),
    url(r'^signin$', views_signin, name="signin"),
    url(r'^signup$', views_signup, name="signup"),
    url(r'^micuenta$', views.miCuenta, name='miCuenta'),
    url(r'^creartest$', views.crearTest, name="crearTest"),
    url(r'^crearencuesta$', views.crearEncuesta, name = "crearEncuesta"),
    url(r'^logoutview$', views.logoutView, name = "logoutView"),
    url(r'^home$', views.home, name = "home"),
    
]

templates/badattempt.html
Has entrado mal

usuario => {{user}}
hashlinkmail => {{hashlinkmail}}
hashlinkuser => {{hashlinkuser}}

templates/base.html
{% load staticfiles %}
{% block head %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="media/media/favicon.ico?ver=2.0" type="image/x-icon"/>
    <title>{{pagetitle|default:"Tests4all"}}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'testsforall/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/image-select.css' %}" />
    <link rel="stylesheet" href="{% static 'css/image-select2.css' %}" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="{% static 'js/image-select.js' %}"></script>
    <script src="https://use.fontawesome.com/57e0f545e7.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="{% static 'js/dirPagination.js' %}"></script>
    {% block extra_head %}{% endblock %}
</head>
{% endblock %}

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            {% if user.is_authenticated %}
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'testsforall:home' %}">Tests4all, {{user.username}}</a>
            </div>
            
            <ul class="nav navbar-nav">
                <div id="icono-menu">
                    <div id="keep-open">
                        <button type="button" class=" btn-menu btn btn-default navbar-btn dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-align-justify"></span>
                        </button>
                        <ul id="menu-dropdown" class="dropdown-menu">
                            <li><a href="{% url 'testsforall:home' %}">Home</a></li>
                            <li><a href="{% url 'testsforall:surveysToDo' %}">Por realizar</a></li>
                            <li><a href="#">Realizados</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Blog</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Ajustes</a></li>
                            
                            <li><a href="{% url 'testsforall:logoutView' %}">Cerrar sesión</a></li>
                            
                        </ul>
                    </div>
                </div>
            </ul>
            <div id="friendsrequest">
                <a class="btn btn-info" href="{% url 'testsforall:friendRequests' %}">Solicitudes de amistad</a>
            </div>
            {% else %}
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'testsforall:home' %}">Entrar <i class="fa fa-sign-in"></i></a>
            </div>
            {% endif %}
            
        </div>
    </nav>
    
    
    {% block base %}

    <div class="container">

        {% if messages %}
        <ul class="messages messages-margin">
            {% for message in messages %}
            <li class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="container-fluid">
            {% block content %}{%endblock%}
        </div>

    </div>
    <script>
    $(document).ready(function() {
        $(".btn-menu").on("click", function() {
            $(".navbar-brand").animate({
                width: 'toggle'
            });
        });

        $('#keep-open').on({
            "shown.bs.dropdown": function() {
                this.closable = false;
            },
            "click": function() {
                this.closable = true;
            },
            "hide.bs.dropdown": function() {
                return this.closable;
            }
        });


    });
</script>
    
    {% block scripts %}{%endblock%}

    <div id="crearModal" class="modal-crear modal fade" role="dialog">
        <div class="modal-dialog col-xs-12">
            <div class="modal-content col-xs-12">
                <div class="modal-header col-xs-12">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Crear...</h4>
                </div>
                <div class="modal-body text-center col-xs-12">
                    <div class="col-xs-6 text-center">
                        <a class="col-xs-8 btn btn-info" href="{% url 'testsforall:crearTest'%}">Crear Test</a>
                    </div>
                    <div class="col-xs-6 text-center">
                        <a class="col-xs-8 btn btn-info" href="{% url 'testsforall:crearEncuesta'%}">Crear Encuesta</a>
                    </div>
                </div>
                <div class="modal-footer col-xs-12">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
    
        </div>
    </div>

</body>
{% endblock %}


</html>

templates/checkmail.html
{% extends 'base.html' %} {% block content %}
Bien para completar el proceso de registro deberás confirmar tu correo accediendo a él y dándole al link que te hemos enviado.
{% endblock %}

templates/signin.html
{% load staticfiles %}{% load crispy_forms_tags %}
<!DOCTYPE html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="/media/bft/Favicon.ico">
    <title>{{pagetitle|default:"Brave Frontier Teams"}}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'testsforall/style.css' %}" />
</head>

<body>
    <div class="container">

        {% if messages %}
        <ul class="messages messages-margin">
            {% for message in messages %}
            <li class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="container-fluid">
            <h2>{{titulo|default:"Login"}}</h2>
            <div class="row-form">
                {% crispy form %}
            </div>
        </div>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>

</html>

templates/signup.html
{% extends 'base.html' %} {% block content %}
<h2>Registro</h2>
<p>Bienvenido a Tests4all completa el siguiente formulario para poder empezar a crear tus tests</p>
<form method="post" id="signupform">
  {% csrf_token %}
  <div class="col-xs-12 col-sm-6 signupfield">
    <label for="username">Indica el nombre de usuario deseado</label>
    <div class="inner-addon left-addon">
      <i class="glyphicon glyphicon-user"></i>
      <input type="text" id="username" name="username" class="form-control" />
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 signupfield">
    <label for="email">Indica tu e-mail</label>
    <div class="inner-addon left-addon">
      <i class="fa fa-envelope-o"></i>
      <input type="email" id="email" name="email" class="form-control" />
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="col-xs-12 col-sm-6 signupfield">
    <label for="password">Contraseña deseada</label>
    <div class="inner-addon left-addon">
      <i class="fa fa-key"></i>
      <input type="password" id="password" name="password" class="form-control" />
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 signupfield">
    <label for="password2">Confirma la contraseña</label>
    <div class="inner-addon left-addon">
      <i class="fa fa-key"></i>
      <input type="password" id="password2" name="password2" class="form-control" />
    </div>
  </div>
  <button type="button" id="submitsignup" class="btn btn-success">Sign up</button>
</form>
<div class="collapse alert alert-danger" id="notfullform">
  El formulario no està completo
</div>
<div class="collapse alert alert-danger col-xs-8" id="infousername">
  Ya existe este usuario
</div>
<div class="collapse alert alert-danger col-xs-8" id="infomail">
  Ya existe un usuario que ha usado este correo electrónico
</div>
<div class="collapse alert alert-danger" id="passwordwrong">
  Las contraseñas no coinciden.
</div>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $(document).ready(function(){
    var formok = true;
    $('#submitsignup').click(function(event){
      usernameExists();
      mailExists();
      if(!formFull()){
        formok = false;
        $('#notfullform').css('visibility','visible').hide().fadeIn().removeClass('hidden');
        setTimeout(hideNotFullForm, 4000);
      }
      if(!checkPassword()){
        formok = false;
        $('#passwordwrong').css('visibility','visible').hide().fadeIn().removeClass('hidden');
        setTimeout(hideWrongPassword, 4000);
      }
      if(formok){
        $('#signupform').submit();
      }
      formok = true;
    });
    
    
    function usernameExists() {
      var username = $('#username').val();
      var token = $("input[name=csrfmiddlewaretoken]").val();
      $.ajax({
        async: false,
        type: 'POST',
        url: "{% url 'testsforall:checkuser' %}",
        data: {
          'csrfmiddlewaretoken': token,
          'username': username,
        },
        success: function(data) {
          if (data[0].userexists) {
            formok = false;
            $('#infousername').css('visibility', 'visible').hide().fadeIn().removeClass('hidden');
            setTimeout(hideInfousername, 4000);
          }
        },
        error: function(xhr, ajaxOptions, thrownError) {
          alert('Ha habido algun problema al consultar el username');
          console.log(xhr.status);
          console.log(thrownError);
        }
      });
    }
    
    function mailExists() {
      var mail = $('#email').val();
      var token = $("input[name=csrfmiddlewaretoken]").val();
      $.ajax({
        async: false,
        type: 'POST',
        url: "{% url 'testsforall:checkmail' %}",
        data: {
          'csrfmiddlewaretoken': token,
          'mail': mail,
        },
        success: function(data) {
          if (data[0].mailexists) {
            formok = false;
            $('#infomail').css('visibility', 'visible').hide().fadeIn().removeClass('hidden');
            setTimeout(hideInfomail, 4000);
          }
        },
        error: function(xhr, ajaxOptions, thrownError) {
          alert('Ha habido algun problema al consultar el username');
          console.log(xhr.status);
          console.log(thrownError);
        }
      });
    }
    
    function formFull(){
      var username = $('#username').val();
      var email = $('#email').val();
      var password = $('#password').val();
      var password2 = $('#password2').val();
      if(username == ''){
        return false;
      }
      else if(email == ''){
        return false;
      }
      else if(password == ''){
        return false;
      }
      else if(password2 == ''){
        return false;
      }
      else{
        return true;
      }
    }
    function checkPassword(){
      var password = $('#password').val();
      var password2 = $('#password2').val();
      return password == password2;
    }
    
    function hideInfousername(){
      $('#infousername').fadeOut();
    }
    
    function hideInfomail(){
      $('#infomail').fadeOut();
    }
    
    function hideWrongPassword(){
      $('#passwordwrong').fadeOut();
    }
    function hideNotFullForm(){
      $('#notfullform').fadeOut();
    }
  });  
</script>
{% endblock %}

templates/welcome.html
{% extends 'base.html' %} {% block content %}
Tu proceso de registro se ha completado satisfactoriamente, inicia sesion para poder empezar a hacer tus tests!
<a class="btn btn-info" href="{% url 'testsforall:signin' %}">Login</a>
{% endblock %}

templates/welcomemail.html
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .button {
            border: solid 2px #088a29;
            border-radius: 5px;
            padding: 0.5em;
            background: #74df00;
            margin-top: 1.5em;
            font-weight: 800;
            font-family: lucida sans unicode;
            color: white;
            text-decoration: none;
        }
        body {
               padding: 2em;
        }
        #notes{
            font-size: smaller;
            margin-top: 3em;
        }
    </style>
</head>

<body>
    <h2>{{user.user.username}}, bienvenido a </h2>
    <img src="cid:logo.png">
    <p>
        Ya estás más cerca de completar el proceso de registro y poder empezar a crear tus propios tests.<br>
        Dale a este botón para poder completar el proceso de registro
    </p>
    <br>
    <a class="button" href="https://miniprojecte-wijan.c9users.io{% url 'testsforall:confirmmail' hashlink user.id %}">Confirmar mail</a>
    <p id="notes">*¿No has iniciado tú el proceso de registro en tests4all? Entonces ignora este correo, en un plazo de 3 días borraremos todos los datos relacionados con este correo</p>
</body>

</html>