miniprojecte/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings

urlpatterns =([
    url(r'^', include('testsforall.urls', namespace="testsforall")),
    ]
    + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

testsforall/urls.py
from django.conf.urls import url

from . import views
from usuarios.views import views_signin, views_signup, views_checkuser, views_checkmail, views_confirmmail
urlpatterns = [
    url(r'^solvetest', views.solveTest, name = "solveTest"),
    url(r'^getsurveystodo', views.getSurveysToDo, name = "getSurveysToDo"),
    url(r'^surveystodo$', views.surveysToDo, name = "surveysToDo"),
    url(r'^getmygroups', views.getMyGroups, name = "getMyGroups"),
    url(r'^creategroup', views.createGroup, name = "createGroup"),
    url(r'^user/(?P<idUser>[0-9]+)/', views.user, name = "user"),
    url(r'^friendrequests', views.friendRequests, name = "friendRequests"),
    url(r'^sendfriendrequest', views.sendFriendRequest, name = "sendFriendRequest"),
    url(r'^acceptfriend', views.acceptFriend, name = "acceptFriend"),
    url(r'^getusers$', views.getUsers, name = "getUsers"),
    url(r'^getfriendrequests', views.getFriendRequests, name = "getFriendRequests"),
    url(r'^getfriends$', views.getFriends, name = "getFriends"),
    url(r'^social', views.social, name = "social"),
    url(r'^confirmmail/(?P<hashlink>[a-fA-F\d]*)/(?P<userid>[0-9]+)', views_confirmmail, name="confirmmail"),
    url(r'^checkmail$', views_checkmail, name="checkmail"),
    url(r'^checkuser$', views_checkuser, name="checkuser"),
    url(r'^saveanswer$', views.save_answer, name = "save_answer"),
    url(r'^savequestion$', views.save_question, name = "save_question"),
    url(r'^editsurvey/(?P<idSurvey>[0-9]+)/', views.edit_survey, name = "edit_survey"),
    url(r'^publish/(?P<idSurvey>[0-9]+)/', views.publish_survey, name = "publish_survey"),
    url(r'^getsurveys$', views.getSurveys, name = "getSurveys"),
    url(r'^misencuestas$', views.mySurveys, name = "mySurveys"),
    url(r'^deletesurvey/(?P<idSurvey>[0-9]+)/', views.deleteSurvey, name = "deleteSurvey"),
    url(r'^survey/(?P<idSurvey>[0-9]+)/', views.survey, name = "survey"),
    url(r'^$', views.index, name="index"),
    url(r'^upload$', views.upload, name ='jfu_upload'),
    url(r'^upload/(?P<idSurvey>[0-9]+)$', views.upload, name = 'jfu_upload_edit'),
    url(r'^deleteupload/(?P<pk>\d+)$', views.upload_delete, name ='jfu_delete'),
    url(r'^signin$', views_signin, name="signin"),
    url(r'^signup$', views_signup, name="signup"),
    url(r'^micuenta$', views.miCuenta, name='miCuenta'),
    url(r'^creartest$', views.crearTest, name="crearTest"),
    url(r'^crearencuesta$', views.crearEncuesta, name = "crearEncuesta"),
    url(r'^logoutview$', views.logoutView, name = "logoutView"),
    url(r'^home$', views.home, name = "home"),
    
]

testsforall/views.py
import os, datetime
from django.conf import settings
from django.core.urlresolvers import reverse
from django.views import generic
from django.views.decorators.http import require_POST
from jfu.http import upload_receive, UploadResponse, JFUResponse
from django.shortcuts import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from testsforall.models import Survey, UserTests, Group, Encuesta, Image, Question, Answer, Test, FriendRequest, Result
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpRequest, HttpResponseRedirect, JsonResponse
import json
from django.db.models import Q
from django.core import serializers




def index(request):
    
    return render(request, 'testsforall/index.html')


def logoutView(request):
    logout(request)
    messages.info(request, 'Has cerrado sesion correctamente')
    return redirect('testsforall:index')
    
def signup(request):
    return redirect('testsforall:signup')
    
@login_required    
def home(request):
    
    return render(request, 'testsforall/home.html')

    
@login_required
def miCuenta(request):
    
    return render(request, 'testsforall/myaccount.html')
    
    
    
@login_required
def mySurveys(request):
    surveys = Survey.objects.filter(creator = request.user.id)
    return render(request, 'testsforall/mysurveys.html', {'surveys': surveys})
    
@login_required    
def crearEncuesta(request):
    
    usertests = UserTests.objects.get( user_id = request.user.id)
    
    if request.method == "POST":
        
        publishsurvey = False
        
        if request.POST.get('published') == "1":
            publishsurvey = True
        
        
        survey = Encuesta(title = request.POST.get('surveytitle'), creator = usertests, created_at = datetime.datetime.now(),
        last_edition = datetime.datetime.now(), future_publication = request.POST.get('future_publication'),
        future_close = request.POST.get('future_close'), published = publishsurvey, typesurvey = "Encuesta")

        survey.save()
        
        #guardar preguntas
        
        for i in range(int(request.POST.get('totalquestions'))):
            nquestion = i+1
            
            if request.POST.get("inputimgquestion"+str(nquestion)):
                imgquestion = Image.objects.get(id = request.POST.get("inputimgquestion"+str(nquestion)))
                question = Question(title = request.POST.get('tq'+str(nquestion)), survey = survey, image = imgquestion)
                question.save()
            else:
                question = Question(title = request.POST.get('tq'+str(nquestion)), survey = survey)
                question.save()
                
            #guardar respuestas
            for i in range(int(request.POST.get('totalanswers'+str(nquestion)))):
                nanswer = i+1
                ans_que = str(nquestion)+"_"+str(nanswer)
                if request.POST.get("inputimganswer"+ans_que):
                    imganswer = Image.objects.get(id = request.POST.get("inputimganswer"+ans_que))
                    answer = Answer(title = request.POST.get("answer"+ans_que), question = question, image = imganswer)
                    answer.save()
                else:
                    answer = Answer(title = request.POST.get("answer"+ans_que), question = question)
                    answer.save()
            #for i in range(int(request.POST.get('')))
        
        if request.POST.get('inputimgsurvey'):
            survey.image.add(request.POST.get('inputimgsurvey'))
        
        
        return HttpResponseRedirect(reverse('testsforall:survey', kwargs={'idSurvey':survey.id}))
 
    images = Image.objects.filter( uploader = usertests.id);
    context = {'images' : images}
    return render(request, 'testsforall/createencuesta.html', context)
    
    
@login_required
@login_required    
def crearTest(request):
    
    usertests = UserTests.objects.get( user_id = request.user.id)
    
    if request.method == "POST":
        
        publishsurvey = False
        
        if request.POST.get('published') == "1":
            publishsurvey = True
        
        
        survey = Test(title = request.POST.get('surveytitle'), rules = request.POST.get('rules'), creator = usertests, created_at = datetime.datetime.now(),
        last_edition = datetime.datetime.now(), future_publication = request.POST.get('future_publication'),
        future_close = request.POST.get('future_close'), published = publishsurvey, typesurvey = request.POST.get('typetest'))
        survey.save()
        #guardar preguntas
        maxresult = 0
        nquestion = 1
        for i in range(1, int(request.POST.get('totalquestions'))):
            question = None
            while(request.POST.get('tq'+str(nquestion)) is None):
                nquestion = nquestion+1
            if request.POST.get("inputimgquestion"+str(nquestion)):
                imgquestion = Image.objects.get(id = request.POST.get("inputimgquestion"+str(nquestion)))
                question = Question(title = request.POST.get('tq'+str(nquestion)), survey = survey, image = imgquestion, value = request.POST.get('pointsperquestioninput'+str(nquestion)))
                question.save()
            else:
                question = Question(title = request.POST.get('tq'+str(nquestion)), survey = survey, value = request.POST.get('pointsperquestioninput'+str(nquestion)))
                question.save()
            maxresult = maxresult+float(question.value)
            
            correctquestion = request.POST.get('correctanswer'+str(nquestion))
                
            #guardar respuestas
            for i in range(int(request.POST.get('totalanswers'+str(nquestion)))):
                nanswer = i+1
                ans_que = str(nquestion)+"_"+str(nanswer)
                answercorrect = correctquestion == nanswer
                if request.POST.get("inputimganswer"+ans_que):
                    imganswer = Image.objects.get(id = request.POST.get("inputimganswer"+ans_que))
                    
                    answer = Answer(title = request.POST.get("answer"+ans_que), question = question, image = imganswer, correct = answercorrect)
                    answer.save()
                else:
                    answer = Answer(title = request.POST.get("answer"+ans_que), question = question, correct = answercorrect)
                    answer.save()
            #for i in range(int(request.POST.get('')))
        
        if request.POST.get('inputimgsurvey'):
            survey.image.add(request.POST.get('inputimgsurvey'))
        
        survey.max_result = maxresult
        survey.save()
        return HttpResponseRedirect(reverse('testsforall:survey', kwargs={'idSurvey':survey.id}))
 
    images = Image.objects.filter( uploader = usertests.id);
    context = {'images' : images}
    return render(request, 'testsforall/createtest.html', context)

@login_required
def deleteSurvey(request, idSurvey):
    survey = get_object_or_404(Survey, id = idSurvey)
    survey.delete()
    messages.error(request, 'Encuesta eliminada correctamente')
    return HttpResponseRedirect(reverse('testsforall:mySurveys'))

@login_required
def survey(request, idSurvey):
    survey = get_object_or_404(Survey, id=idSurvey)
    return render(request, 'testsforall/viewsurvey.html', {'survey': survey})
    
@login_required    
def creados(request):
    
    tests = Survey.objects.all();
    context = {'tests': tests}
    return render(request, 'testsforall/created.html', context)



def getSurveys(request):
    usertests = UserTests.objects.get(user = request.user.id)
    surveys = Survey.objects.filter(creator = usertests);
    #data = serializers.serialize('json', [obj,])
    #struct = json.loads(data)
    #data = json.dumps(struct[0])
    resposta = list()
    for enquesta in surveys:
        firstimage = str(enquesta.getFirstImage())
        created_date = enquesta.created_at.strftime('%d-%m-%Y')
        last_edition_date = enquesta.last_edition.strftime('%d-%m-%Y')
        if enquesta.future_publication is not None:
            future_publication_date = enquesta.future_publication.strftime('%d-%m-%Y')
        else:
            future_publication_date = 'No hay fecha de publicacion futura'
        if enquesta.future_close is not None:
            future_close_date = enquesta.future_close.strftime('%d-%m-%Y')
        else:
            future_close_date = 'No hay fecha de cierre futura'
        
        resposta.append({
            'id': enquesta.id,
            'typesurvey': enquesta.typesurvey,
            'creator': enquesta.creator.id,
            'title': enquesta.title,
            'created_at': created_date,
            'last_edition': last_edition_date,
            'future_publication': future_publication_date,
            'future_close': future_close_date,
            'published': enquesta.published,
            'image': firstimage
        });
        
    respostaserialitzada = json.dumps(resposta);
    return HttpResponse(respostaserialitzada, content_type='text/json')


@require_POST
def upload( request ):

    # The assumption here is that jQuery File Upload
    # has been configured to send files one at a time.
    # If multiple files can be uploaded simulatenously,
    # 'file' may be a list of files.
    imagen = upload_receive( request )

    usertests = UserTests.objects.get( user_id = request.user.id )
    instance = Image( image = imagen, uploader = usertests )
    instance.save()

    basename = os.path.basename( instance.image.path )
    namepath = "media/"+basename

    file_dict = {
        'name' : basename,
        'size' : imagen.size,
        
        'id' : instance.pk,

        'url': settings.MEDIA_URL + namepath,
        'thumbnailUrl': "/"+settings.MEDIA_URL + namepath,

testsforall/templates/testsforall/creategroup.html
{% extends 'base.html' %}{% block content %}
{% endblock %}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    var app = angular.module('myFriends', ['angularUtils.directives.dirPagination']);


    app.config(function($interpolateProvider) {
        $interpolateProvider.startSymbol('[[');
        $interpolateProvider.endSymbol(']]');
    });
    app.controller('friends', function($scope, $http) {
        $http({
            method: 'GET',
            url: 'http://miniprojecte-wijan.c9users.io/getfriends'
        }).then(function successCallback(response) {
            // this callback will be called asynchronously
            // when the response is available
            $scope.friends = response.data;
        }, function errorCallback(response) {
            // called asynchronously if an error occurs
            // or server returns response with an error status.
            alert(response);

        });

        $scope.sort = function(keyname) {
            $scope.sortKey = keyname; //set the sortKey to the param passed
            $scope.reverse = !$scope.reverse; //if true make it false and vice versa
        };
    });
</script>

testsforall/templates/testsforall/friendsrequests.html
{% extends 'base.html' %}{% block content %}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
var app = angular.module('myFriendRequests', ['angularUtils.directives.dirPagination']);
    
    
    app.config(function($interpolateProvider) {
      $interpolateProvider.startSymbol('[[');
      $interpolateProvider.endSymbol(']]');
    });
    
    app.controller('requests', function($scope, $http) {
        $http({
            method: 'GET',
            url: 'http://miniprojecte-wijan.c9users.io/getfriendrequests'
        }).then(function successCallback(response) {
            // this callback will be called asynchronously
            // when the response is available
            $scope.requests = response.data;
        }, function errorCallback(response) {
                // called asynchronously if an error occurs
                // or server returns response with an error status.
                alert(response);
            
        });
        
        $scope.acceptFriend = function(requestid) {
            var button = $('.addfriend[data-requestid="'+requestid+'"]');
            var token = $("input[name=csrfmiddlewaretoken]").val();
            $.ajax({
                type: 'POST',
                url: "{% url 'testsforall:acceptFriend' %}",
                data: {
                    'csrfmiddlewaretoken': token,
                    'requestid': requestid,
                },
                success: function(msg) {
                    var returndata = msg[0].msg;
                    $('#infoajax').text(returndata);
                    $('#infoAjaxModal').modal('show');
                    var parent = button.parent();
                    button.toggle();
                    button.siblings('.rejectFriend').first().toggle();
                    parent.text('Amistad aceptada');
                    //alert(msg.msg);
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert('Ha habido algun problema al enviar la solicitud de amistad');
                    console.log(xhr.status);
                    console.log(thrownError);
                }
            });
        }
        
        $scope.sort = function(keyname){
            $scope.sortKey = keyname;   //set the sortKey to the param passed
            $scope.reverse = !$scope.reverse; //if true make it false and vice versa
        };
    
    });
    
</script>
<div class="container" ng-app="myFriendRequests" ng-controller="requests">
    {% csrf_token %}
    <h2>Solicitudes de amistad</h2>
    <form class="form-inline">
        <div class="form-group">
            <label >Buscador</label>
            <input type="text" ng-model="search" class="form-control" placeholder="Introduce la solicitud a buscar">
        </div>
    </form>
    
    <!--
    <thead>
        <tr>
            <th ng-click="sort('id')">Id</th>
            <th ng-click="sort('first_name')">First Name</th>
            <th ng-click="sort('last_name')">Last Name</th>
            <th ng-click="sort('hobby')">Hobby</th>
        </tr>
    </thead>
    -->
    <table id="myrequests" class="table-hover table-bordered table col-sm-12">
        <thead>
            <tr>
                <td ng-click="sort('petitioner')">
                    Usuario
                    <span class="glyphicon sort-icon" ng-show="sortKey=='usuario'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                </td>
                <td ng-click="sort('daterequest')">
                    Fecha de solicitud
                    <span class="glyphicon sort-icon" ng-show="sortKey=='daterequest'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                </td>
                <td>Acciones</td>
            </tr>

        </thead>
        <tr dir-paginate="request in requests|orderBy:sortKey:reverse|filter:search|itemsPerPage:10">
            <td>
                <a href="user/[[request.petitionerid]]">[[ request.petitioner ]]</a>
            </td>
            <td>
                [[request.daterequest]]
            </td>
            <td>
                <a class="btn accion btn-success" data-requestid = "[[request.requestid]]" ng-click="acceptFriend(request.requestid)"><i class="fa fa-plus-square"></i> Aceptar</button>
                <a class="btn accion btn-danger" data-requestid = "[[request.requestid]]" ng-click="rejectFriend(request.requestid)"><i class="fa fa-remove"></i> Rechazar</button>
            </td>
        </tr>

    </table>
    <div ng-hide="requests.length">No tienes solicitudes de amistad</div>
    <dir-pagination-controls
       max-size="10"
       direction-links="true"
       boundary-links="true" >
    </dir-pagination-controls>

</div>
<div id="infoAjaxModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content col-xs-12">
            <div class="modal-header col-xs-12">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Solicitud de amistad aceptada</h4>
            </div>
            <div id="infoajax" class="modal-body text-center col-xs-12">
            
            </div>
            <div class="modal-footer col-xs-12">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>


{% endblock %}

testsforall/templates/testsforall/home.html
{% extends 'base.html' %}{% block content %}
<div class="container">
    <h2>HomePage</h2>
    
    <div class="container col-xs-12">
        <div class="col-xs-6">
            <a href="#" data-toggle="modal" data-target="#crearModal" class="btn btn-info col-xs-3">
                <i class="fa fa-pencil"></i> Crear...
            </a>
        </div>
        <div class="col-xs-6">
            <a class="btn btn-info col-xs-3" href="{% url 'testsforall:mySurveys' %}">
                <i class="fa fa-list"></i> Creados
            </a>      
        </div>
        <div class="clearfix col-xs-12"></div>
        <div class="col-xs-6">
            <a class="btn btn-info col-xs-3">
                <i class="fa fa-indent"></i> Por realizar
            </a>  
        </div>
        <div class="col-xs-6">
            <a class="btn btn-info col-xs-3">
                <i class="fa fa-check-square-o"></i> Realizados
            </a>  
        </div>
        
    </div>
</div>
{% endblock %}

testsforall/templates/testsforall/image.html
<img src = "miniprojecte/media/media/superman.png">

testsforall/templates/testsforall/index.html
{% extends 'base.html' %}{% block content %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />

<script src="{% static 'js/index-colors.js' %}"></script>
<div class="container text-center" id="gradient">
    <h2>Tests4all</h2>
    
    <div class="explain center-block">
        La forma más simple y rápida de hacer tests y enviarlos a quien tu quieras.
    </div>
    <div class="explain explain2 center-block">
        <div class="subexplain">
            Quieres hacer tests?
        </div>
        <div class="subexplain">
            O prefieres hacer encuestas?
        </div>
        <div class="subexplain center-block"></div>
    </div>
    
</div>
{% endblock %}

testsforall/templates/testsforall/myaccount.html
{% extends 'base.html' %}{% block content %}
<div class="container">
    <h2>Tests4all</h2>    
</div>
{% endblock %}

testsforall/templates/testsforall/social.html
{% extends 'base.html' %}{% block content %}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    var app = angular.module('myFriends', ['angularUtils.directives.dirPagination']);


    app.config(function($interpolateProvider) {
        $interpolateProvider.startSymbol('[[');
        $interpolateProvider.endSymbol(']]');
    });

    app.controller('friends', function($scope, $http) {
        $http({
            method: 'GET',
            url: 'http://miniprojecte-wijan.c9users.io/getfriends'
        }).then(function successCallback(response) {
            // this callback will be called asynchronously
            // when the response is available
            $scope.friends = response.data;
        }, function errorCallback(response) {
            // called asynchronously if an error occurs
            // or server returns response with an error status.
            alert(response);

        });

        $scope.sort = function(keyname) {
            $scope.sortKey = keyname; //set the sortKey to the param passed
            $scope.reverse = !$scope.reverse; //if true make it false and vice versa
        };
    });

    app.controller('searchfriends', function($scope, $http) {
        $http({
            method: 'GET',
            url: 'http://miniprojecte-wijan.c9users.io/getusers'
        }).then(function successCallback(response) {
            $scope.userstoadd = response.data;
        }, function errorCallback(response) {
            alert(response);
        });
        $scope.sendFriendRequest = function(requested) {
            var idrequested = requested;
            var button = $('.addfriend[data-iduser="'+idrequested+'"]');
            var token = $("input[name=csrfmiddlewaretoken]").val();
            $.ajax({
                type: 'POST',
                url: "{% url 'testsforall:sendFriendRequest' %}",
                data: {
                    'csrfmiddlewaretoken': token,
                    'requested': idrequested,
                },
                success: function(msg) {
                    var returndata = msg[0].msg;
                    $('#infoajax').text(returndata);
                    $('#infoAjaxModal').modal('show');
                    var parent = button.parent();
                    button.toggle();
                    parent.text('Solicitud enviada');
                    //alert(msg.msg);
                },
                error: function(xhr, ajaxOptions, thrownError) {
                    alert('Ha habido algun problema al enviar la solicitud de amistad');
                    console.log(xhr.status);
                    console.log(thrownError);
                }
            });
        }

        $scope.sort = function(keyname) {
            $scope.sortKey = keyname; //set the sortKey to the param passed
            $scope.reverse = !$scope.reverse; //if true make it false and vice versa
        };
    });
</script>

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#myFriends" aria-controls="home" role="tab" data-toggle="tab"><i class="fa fa-user-circle"></i> Mis amigos</a></li>
    <li role="presentation"><a href="#addfriends" aria-controls="profile" role="tab" data-toggle="tab"><i class="fa fa-user-plus"></i> Buscador de amigos</a></li>
    <li role="presentation"><a href="#groups" aria-controls="messages" role="tab" data-toggle="tab"><i class="fa fa-users"></i> Grupos</a></li>
</ul>
<div class="tab-content" ng-app="myFriends">
    <div role="tabpanel" class="tab-pane active" id="myFriends">
        <div class="container" ng-controller="friends">
            <h2>Amigos</h2>
            {% csrf_token %}
            <form class="form-inline">
                <div class="form-group">
                    <label>Buscador</label>
                    <input type="text" ng-model="search" class="form-control" placeholder="Introduce el amigo a buscar">
                </div>
            </form>

            <!--
    <thead>
        <tr>
            <th ng-click="sort('id')">Id</th>
            <th ng-click="sort('first_name')">First Name</th>
            <th ng-click="sort('last_name')">Last Name</th>
            <th ng-click="sort('hobby')">Hobby</th>
        </tr>
    </thead>
    -->
            <table id="myfriends" class="table-hover table-bordered table col-sm-12" >
                <thead>
                    <tr>
                        <td ng-click="sort('username')">
                            Usuario
                            <span class="glyphicon sort-icon" ng-show="sortKey=='username'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                        </td>
                        <td ng-click="sort('datefriends)">
                            Amigos desde
                            <span class="glyphicon sort-icon" ng-show="sortKey=='datefriends'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                        </td>
                        <td ng-click="sort('dateuser')">
                            En tests4all desde
                            <span class="glyphicon sort-icon" ng-show="sortKey=='dateuser'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                        </td>
                        <td>Acciones</td>
                    </tr>

                </thead>
                <tr dir-paginate="friend in friends|orderBy:sortKey:reverse|filter:search|itemsPerPage:10">
                    <td>
                        <a href="user/[[friend.id]]">[[ friend.username ]]</a>
                    </td>
                    <td>
                        [[friend.datefriends]]
                    </td>
                    <td>
                        [[friend.dateuser]]
                    </td>
                    <td>
                        <a class="btn accion btn-danger" href="deleteSurvey/[[survey.id]]"><i class="fa fa-trash"></i> Eliminar amigo</button>
                    </td>
                </tr>
            </table>
            <div ng-hide="friends.length">Aún no tienes amigos</div>
            <dir-pagination-controls
               max-size="10"
               direction-links="true"
               boundary-links="true" >
            </dir-pagination-controls>

        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="addfriends" ng-controller="searchfriends">
        <div class="container">
            <h2>Buscador de amigos</h2>
            <form class="form-inline">
                <div class="form-group">
                    <label>Buscador</label>
                    <input type="text" ng-model="search" class="form-control" placeholder="Introduce el amigo a añadir">
                </div>
            </form>

            <!--
    <thead>
        <tr>
            <th ng-click="sort('id')">Id</th>
            <th ng-click="sort('first_name')">First Name</th>
            <th ng-click="sort('last_name')">Last Name</th>
            <th ng-click="sort('hobby')">Hobby</th>
        </tr>
    </thead>
    -->
            <table id="posiblefriends" class="table-hover table-bordered table col-sm-12" >
                <thead>
                    <tr>
                        <td ng-click="sort('username')">
                            Usuario
                            <span class="glyphicon sort-icon" ng-show="sortKey=='username'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                        </td>
                        <td ng-click="sort('datefriends')">
                            En tests4all desde
                            <span class="glyphicon sort-icon" ng-show="sortKey=='datefriends'" ng-class="{'glyphicon-chevron-up':reverse,'glyphicon-chevron-down':!reverse}"></span>
                        </td>
                        <td>Acciones</td>
                    </tr>

                </thead>
                <tr dir-paginate="user in userstoadd|orderBy:sortKey:reverse|filter:search|itemsPerPage:10">
                    <td>
                        <a href="user/[[user.id]]">[[ user.username ]]</a>
                    </td>
                    <td>
                        [[user.created_at]]
                    </td>
                    <td>
                        <button data-iduser="[[user.id]]" class="addfriend btn accion btn-success" ng-click="sendFriendRequest(user.id)"><i class="fa fa-plus-square"></i> Añadir amigo</button>
                    </td>
                </tr>
            </table>
            <div ng-hide="userstoadd.length">Tienes agregados como amigos a todos los usuarios :D</div>
            <dir-pagination-controls
               max-size="10"
               direction-links="true"
               boundary-links="true" >
            </dir-pagination-controls>

        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="groups">
        <div ng-hide="userstoadd.length">No estás en ningún grupo</div>
        <a href="{% url 'testsforall:createGroup' %}" class="btn btn-success"><i class="fa fa-users"></i>Crear grupo</a>
        
    </div>
  </div>
  
<div id="infoAjaxModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content col-xs-12">
            <div class="modal-header col-xs-12">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Solicitud de amistad enviada</h4>
            </div>
            <div id="infoajax" class="modal-body text-center col-xs-12">
            
            </div>
            <div class="modal-footer col-xs-12">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>




{% endblock %}

testsforall/templates/testsforall/upload.html
{% extends 'jfu/upload_form.html' %}

{% block JS_OPTS %}
autoUpload: false,
maxNumberOfFiles: 5,
sequentialUploads: true,
{% endblock %}